const express=require("express");
const bodyParser=require('body-parser');
const helmet=require('helmet');
const morgan=require('morgan');
const cors=require('cors');
const mongoose=require('mongoose');
const app=express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended:false}));
app.use(helmet());
app.use(morgan("dev"));
app.use(cors());
mongoose.connect("mongodb+srv://kartikkysp12:kartik@cluster0.lhleyej.mongodb.net/ecommerce?retryWrites=true&w=majority");
const userRoutes=require("./routes/user_routes");
app.use("/api/user",userRoutes);
const categoryRoutes=require("./routes/categories_routes");
app.use("/api/category",categoryRoutes);
const productRoutes=require("./routes/product_routes");
app.use("/api/products",productRoutes);
const cartRoutes=require("./routes/cart_routes");
app.use("/api/cart",cartRoutes);
const orderRoutes=require("./routes/order_routes");
app.use("/api/order",orderRoutes);
const PORT=5000;
app.listen(PORT,()=>console.log('Server started at port number: ${PORT}'));
